# settings:

# general config
device: "cuda"
seed: 42

# data config
data:
  # all config set in dataloader.py in here
  dataset: "ID_card" # name of the dataset
  data_path: "/home/le/capture_classify/data/data_final.csv" # file included full path to image file its label and usage (used for train, valid or test)
  # classes_file: "../data/classes.json"

  mean: [0.5473038, 0.50469655, 0.48768175]
  std: [0.31888515, 0.31036356, 0.3118952]

  input_size: [640, 640]
  batch_size: 16
  num_workers: 4
  method: "contrast"

# network config
network:
  # all config set in nets.py in here
  backbone: "efficientnet_b0" # name of the backbone architecture
  embedding_size: 128
  num_classes: 2
  freeze_params:
    back_layer: True
    head_layer: False
  drop_rate: 0.2

# learning rate policy
lr_policy:
  name: "adam" # [adam | sgd]
  init_lr:  0.001 # [adam: 3e-4 | sgd: 1e-2]
  momentum: 0.937
  weight_decay: 0.0005
  # adam
  amsgrad: True
  # sgd
  nesterov: True

# scheduler config
scheduler:
  name: "cosine_annealing_R"
  # cosine annealing warm restarts
  T_0: 10
  T_mult: 2
  eta_min: 0.0000001

# loss config
loss:
  name: "bce_loss"
  # num_task: 22
  pos_weight: [0.5]

# train config
num_epochs: 50
checkpoint_period: 25
output_dir: "../models"
